USE [GoldmineUAT]
GO

/****** Object:  StoredProcedure [dbo].[CONTACT2ChangeTracking]    Script Date: 03/12/2018 15:41:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO









ALTER PROCEDURE [dbo].[CONTACT2ChangeTracking] @LastVersionNumber int
as

DECLARE @UEMAILADDR int = COLUMNPROPERTY(
   OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UEMAILADDR', 'ColumnId')

DECLARE @USTAGE1DAT int = COLUMNPROPERTY(
   OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'USTAGE1DAT', 'ColumnId')

DECLARE @UCONVDATE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UCONVDATE', 'ColumnId')

DECLARE @UBCASEOWN int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UBCASEOWN', 'ColumnId')

DECLARE @UCPPOST int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UCPPOST', 'ColumnId')

DECLARE @UCPEMAIL int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UCPEMAIL', 'ColumnId')

DECLARE @UCPPHONE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UCPPHONE', 'ColumnId')

DECLARE @UCPSMS int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UCPSMS', 'ColumnId')

DECLARE @UY12COM int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY12COM', 'ColumnId')

DECLARE @UY13COM int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY13COM', 'ColumnId')

DECLARE @UY14COM int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY14COM', 'ColumnId')

DECLARE @UY15COM int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY15COM', 'ColumnId')

DECLARE @UY16COM int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY16COM', 'ColumnId')

DECLARE @UY17COM int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY17COM', 'ColumnId')

DECLARE @UY18COM int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY18COM', 'ColumnId')

DECLARE @UY19COM int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY19COM', 'ColumnId')

DECLARE @UY20COM int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY20COM', 'ColumnId')

DECLARE @UY21COM int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY21COM', 'ColumnId')

DECLARE @UY22COM int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY22COM', 'ColumnId')

DECLARE @UDOB int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UDOB', 'ColumnId')

	DECLARE @U14SERVT int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U14SERVT', 'ColumnId')
	DECLARE @U15SERVT int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U15SERVT', 'ColumnId')
	DECLARE @U16SERVT int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U16SERVT', 'ColumnId')
	DECLARE @U17SERVT int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U17SERVT', 'ColumnId')
	DECLARE @U18SERVT int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U18SERVT', 'ColumnId')
	DECLARE @U19SERVT int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U19SERVT', 'ColumnId')
	DECLARE @U20SERVT int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U20SERVT', 'ColumnId')

	DECLARE @UY14TYPE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY14TYPE', 'ColumnId')
	DECLARE @UY15TYPE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY15TYPE', 'ColumnId')
	DECLARE @U16TYPE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U16TYPE', 'ColumnId')
	DECLARE @U17TYPE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U17TYPE', 'ColumnId')
	DECLARE @U18TYPE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U18TYPE', 'ColumnId')
	DECLARE @U19TYPE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U19TYPE', 'ColumnId')
	DECLARE @U20TYPE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U20TYPE', 'ColumnId')

	DECLARE @UY14EXPREF int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY14EXPREF', 'ColumnId')
	DECLARE @UY15EXPREF int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY15EXPREF', 'ColumnId')
	DECLARE @U16EXPREF int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U16EXPREF', 'ColumnId')
	DECLARE @U17EXPREF int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U17EXPREF', 'ColumnId')
	DECLARE @U18EXPREF int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U18EXPREF', 'ColumnId')
	DECLARE @U19EXPREF int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U19EXPREF', 'ColumnId')
	DECLARE @U20EXPREF int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U20EXPREF', 'ColumnId')

	DECLARE @UY14EXPFEE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY14EXPFEE', 'ColumnId')
	DECLARE @UY15EXPFEE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY15EXPFEE', 'ColumnId')
	DECLARE @U16EXPFEE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U16EXPFEE', 'ColumnId')
	DECLARE @U17EXPFEE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U17EXPFEE', 'ColumnId')
	DECLARE @U18EXPFEE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U18EXPFEE', 'ColumnId')
	DECLARE @U19EXPFEE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U19EXPFEE', 'ColumnId')
	DECLARE @U20EXPFEE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U20EXPFEE', 'ColumnId')

	DECLARE @UY14USER int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY14USER', 'ColumnId')
	DECLARE @UY15USER int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY15USER', 'ColumnId')
	DECLARE @U16USER int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U16USER', 'ColumnId')
	DECLARE @U17USER int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U17USER', 'ColumnId')
	DECLARE @U18USER int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U18USER', 'ColumnId')
	DECLARE @U19USER int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U19USER', 'ColumnId')
	DECLARE @U20USER int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U20USER', 'ColumnId')

	DECLARE @UY14FEEDAT int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY14FEEDAT', 'ColumnId')
	DECLARE @UY15FEEDAT int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY15FEEDAT', 'ColumnId')
	DECLARE @U16FEEDAT int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U16FEEDAT', 'ColumnId')
	DECLARE @U17FEEDAT int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U17FEEDAT', 'ColumnId')
	DECLARE @U18FEEDAT int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U18FEEDAT', 'ColumnId')
	DECLARE @U19FEEDAT int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U19FEEDAT', 'ColumnId')
	DECLARE @U20FEEDAT int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U20FEEDAT', 'ColumnId')

	DECLARE @UY14SIGNED int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY14SIGNED', 'ColumnId')
	DECLARE @UY15SIGNED int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY15SIGNED', 'ColumnId')
	DECLARE @U16SIGNED int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U16SIGNED', 'ColumnId')
	DECLARE @U17SIGNED int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U17SIGNED', 'ColumnId')
	DECLARE @U18SIGNED int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U18SIGNED', 'ColumnId')
	DECLARE @U19SIGNED int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U19SIGNED ', 'ColumnId')
	DECLARE @U20SIGNED int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U20SIGNED', 'ColumnId')

	DECLARE @UY14ACTREF int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY14ACTREF', 'ColumnId')
	DECLARE @UY15ACTREF int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY15ACTREF', 'ColumnId')
	DECLARE @U16ACTREF int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U16ACTREF', 'ColumnId')
	DECLARE @U17ACTREF int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U17ACTREF', 'ColumnId')
	DECLARE @U18ACTREF int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U18ACTREF', 'ColumnId')
	DECLARE @U19ACTREF int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U19ACTREF', 'ColumnId')
	DECLARE @U20ACTREF int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U20ACTREF', 'ColumnId')

	DECLARE @UY14ACTFEE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY14ACTFEE', 'ColumnId')
	DECLARE @UY15ACTFEE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UY15ACTFEE', 'ColumnId')
	DECLARE @U16ACTFEE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U16ACTFEE', 'ColumnId')
	DECLARE @U17ACTFEE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U17ACTFEE', 'ColumnId')
	DECLARE @U18ACTFEE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U18ACTFEE', 'ColumnId')
	DECLARE @U19ACTFEE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U19ACTFEE', 'ColumnId')
	DECLARE @U20ACTFEE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'U20ACTFEE', 'ColumnId')
	
	DECLARE @USERDEF01 int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'USERDEF01', 'ColumnId')
	DECLARE @USERDEF02 int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'USERDEF02', 'ColumnId')
	DECLARE @UNSOURCE int = COLUMNPROPERTY(
	OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UNSOURCE', 'ColumnId')

select * from (
select *, (select department from dbo.CONTACT1 where ACCOUNTNO = X.Accountno) as 'RECTYPE' from (
SELECT  
    *, 
	[uemailaddrChanged] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UEMAILADDR, SYS_CHANGE_COLUMNS),	
	[ustage1datChanged] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@USTAGE1DAT, SYS_CHANGE_COLUMNS),
	[uconvdatChanged] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UCONVDATE, SYS_CHANGE_COLUMNS),
	[ucppostChanged] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UCPPOST, SYS_CHANGE_COLUMNS),
	[ucpemailChanged] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UCPEMAIL, SYS_CHANGE_COLUMNS),
	[ucpsmsChanged] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UCPSMS, SYS_CHANGE_COLUMNS),
	[ucpphoneChanged] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UCPPHONE, SYS_CHANGE_COLUMNS),
	[ubcaseownChanged] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UBCASEOWN, SYS_CHANGE_COLUMNS),
	[UY12COM] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY12COM, SYS_CHANGE_COLUMNS),
	[UY13COM] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY13COM, SYS_CHANGE_COLUMNS),
	[UY14COM] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY14COM, SYS_CHANGE_COLUMNS),
	[UY15COM] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY15COM, SYS_CHANGE_COLUMNS),
	[UY16COM] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY16COM, SYS_CHANGE_COLUMNS),
	[UY17COM] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY17COM, SYS_CHANGE_COLUMNS),
	[UY18COM] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY18COM, SYS_CHANGE_COLUMNS),
	[UY19COM] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY19COM, SYS_CHANGE_COLUMNS),
	[UY20COM] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY20COM, SYS_CHANGE_COLUMNS),
	[UY21COM] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY21COM, SYS_CHANGE_COLUMNS),
	[UY22COM] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY22COM, SYS_CHANGE_COLUMNS),
	[UDOB] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UDOB, SYS_CHANGE_COLUMNS),

	[U14SERVT] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U14SERVT, SYS_CHANGE_COLUMNS),
	[U15SERVT] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U15SERVT, SYS_CHANGE_COLUMNS),
	[U16SERVT] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U16SERVT, SYS_CHANGE_COLUMNS),
	[U17SERVT] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U17SERVT, SYS_CHANGE_COLUMNS),
	[U18SERVT] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U18SERVT, SYS_CHANGE_COLUMNS),
	[U19SERVT] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U19SERVT, SYS_CHANGE_COLUMNS),
	[U20SERVT] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U20SERVT, SYS_CHANGE_COLUMNS),

	[UY14TYPE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY14TYPE, SYS_CHANGE_COLUMNS),
	[UY15TYPE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY15TYPE, SYS_CHANGE_COLUMNS),
	[U16TYPE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U16TYPE, SYS_CHANGE_COLUMNS),
	[U17TYPE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U17TYPE, SYS_CHANGE_COLUMNS),
	[U18TYPE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U18TYPE, SYS_CHANGE_COLUMNS),
	[U19TYPE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U19TYPE, SYS_CHANGE_COLUMNS),
	[U20TYPE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U20TYPE, SYS_CHANGE_COLUMNS),

	[UY14EXPREF] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY14EXPREF, SYS_CHANGE_COLUMNS),
	[UY15EXPREF] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY15EXPREF, SYS_CHANGE_COLUMNS),
	[U16EXPREF] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U16EXPREF, SYS_CHANGE_COLUMNS),
	[U17EXPREF] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U17EXPREF, SYS_CHANGE_COLUMNS),
	[U18EXPREF] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U18EXPREF, SYS_CHANGE_COLUMNS),
	[U19EXPREF] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U19EXPREF, SYS_CHANGE_COLUMNS),
	[U20EXPREF] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U20EXPREF, SYS_CHANGE_COLUMNS),

	[UY14EXPFEE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY14EXPFEE, SYS_CHANGE_COLUMNS),
	[UY15EXPFEE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY15EXPFEE, SYS_CHANGE_COLUMNS),
	[U16EXPFEE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U16EXPFEE, SYS_CHANGE_COLUMNS),
	[U17EXPFEE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U17EXPFEE, SYS_CHANGE_COLUMNS),
	[U18EXPFEE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U18EXPFEE, SYS_CHANGE_COLUMNS),
	[U19EXPFEE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U19EXPFEE, SYS_CHANGE_COLUMNS),
	[U20EXPFEE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U20EXPFEE, SYS_CHANGE_COLUMNS),

	[UY14USER] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY14USER, SYS_CHANGE_COLUMNS),
	[UY15USER] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY15USER, SYS_CHANGE_COLUMNS),
	[U16USER] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U16USER, SYS_CHANGE_COLUMNS),
	[U17USER] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U17USER, SYS_CHANGE_COLUMNS),
	[U18USER] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U18USER, SYS_CHANGE_COLUMNS),
	[U19USER] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U19USER, SYS_CHANGE_COLUMNS),
	[U20USER] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U20USER, SYS_CHANGE_COLUMNS),

	[UY14FEEDAT] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY14FEEDAT, SYS_CHANGE_COLUMNS),
	[UY15FEEDAT] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY15FEEDAT, SYS_CHANGE_COLUMNS),
	[U16FEEDAT] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U16FEEDAT, SYS_CHANGE_COLUMNS),
	[U17FEEDAT] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U17FEEDAT, SYS_CHANGE_COLUMNS),
	[U18FEEDAT] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U18FEEDAT, SYS_CHANGE_COLUMNS),
	[U19FEEDAT] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U19FEEDAT, SYS_CHANGE_COLUMNS),
	[U20FEEDAT] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U20FEEDAT, SYS_CHANGE_COLUMNS),

	[UY14SIGNED] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY14SIGNED, SYS_CHANGE_COLUMNS),
	[UY15SIGNED] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY15SIGNED, SYS_CHANGE_COLUMNS),
	[U16SIGNED] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U16SIGNED, SYS_CHANGE_COLUMNS),
	[U17SIGNED] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U17SIGNED, SYS_CHANGE_COLUMNS),
	[U18SIGNED] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U18SIGNED, SYS_CHANGE_COLUMNS),
	[U19SIGNED] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U19SIGNED, SYS_CHANGE_COLUMNS),
	[U20SIGNED] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U20SIGNED, SYS_CHANGE_COLUMNS),

	[UY14ACTREF] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY14ACTREF, SYS_CHANGE_COLUMNS),
	[UY15ACTREF] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY15ACTREF, SYS_CHANGE_COLUMNS),
	[U16ACTREF] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U16ACTREF, SYS_CHANGE_COLUMNS),
	[U17ACTREF] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U17ACTREF, SYS_CHANGE_COLUMNS),
	[U18ACTREF] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U18ACTREF, SYS_CHANGE_COLUMNS),
	[U19ACTREF] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U19ACTREF, SYS_CHANGE_COLUMNS),
	[U20ACTREF] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U20ACTREF, SYS_CHANGE_COLUMNS),

	[UY14ACTFEE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY14ACTFEE, SYS_CHANGE_COLUMNS),
	[UY15ACTFEE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UY15ACTFEE, SYS_CHANGE_COLUMNS),
	[U16ACTFEE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U16ACTFEE, SYS_CHANGE_COLUMNS),
	[U17ACTFEE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U17ACTFEE, SYS_CHANGE_COLUMNS),
	[U18ACTFEE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U18ACTFEE, SYS_CHANGE_COLUMNS),
	[U19ACTFEE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U19ACTFEE, SYS_CHANGE_COLUMNS),
	[U20ACTFEE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@U20ACTFEE, SYS_CHANGE_COLUMNS),

	[USERDEF01] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@USERDEF01, SYS_CHANGE_COLUMNS),
	[USERDEF02] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@USERDEF02, SYS_CHANGE_COLUMNS),
	[UNSOURCE] =
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UNSOURCE, SYS_CHANGE_COLUMNS)
	
FROM  
    CHANGETABLE(CHANGES GoldmineUAT.dbo.CONTACT2, 1) AS CT  
) X
where (X.uemailaddrChanged = 1 or X.ustage1datChanged = 1 or X.uconvdatChanged = 1
or X.[ucppostChanged] = 1 or X.[ucpphoneChanged] = 1 or X.[ucpemailChanged] = 1 or X.[ucpsmsChanged] = 1 or X.ubcaseownChanged = 1
or X.UY12COM = 1 or
X.UY13COM = 1 or
X.UY14COM = 1 or
X.UY15COM = 1 or
X.UY16COM = 1 or
X.UY17COM = 1 or
X.UY18COM = 1 or 
X.UY19COM = 1 or
X.UY20COM = 1 or
X.UY21COM = 1 or
X.UY22COM = 1
or X.UDOB = 1

or
X.U14SERVT = 1 or
X.U15SERVT = 1 or
X.U16SERVT = 1 or
X.U17SERVT = 1 or
X.U18SERVT = 1 or
X.U19SERVT = 1 or
X.U20SERVT = 1 or

X.UY14TYPE = 1 or
X.UY15TYPE = 1 or
X.U16TYPE = 1 or
X.U17TYPE = 1 or
X.U18TYPE = 1 or
X.U19TYPE = 1 or
X.U20TYPE = 1 or

X.UY14EXPREF = 1 or
X.UY15EXPREF = 1 or
X.U16EXPREF = 1 or
X.U17EXPREF = 1 or
X.U18EXPREF = 1 or
X.U19EXPREF = 1 or
X.U20EXPREF = 1 or

X.UY14EXPFEE = 1 or
X.UY15EXPFEE = 1 or
X.U16EXPFEE = 1 or
X.U17EXPFEE = 1 or
X.U18EXPFEE = 1 or
X.U19EXPFEE = 1 or
X.U20EXPFEE = 1 or

X.UY14USER = 1 or
X.UY15USER = 1 or
X.U16USER = 1 or
X.U17USER = 1 or
X.U18USER = 1 or
X.U19USER = 1 or
X.U20USER = 1 or

X.UY14FEEDAT = 1 or 
X.UY15FEEDAT = 1 or 
X.U16FEEDAT = 1 or 
X.U17FEEDAT = 1 or 
X.U18FEEDAT = 1 or 
X.U19FEEDAT = 1 or 
X.U20FEEDAT = 1 or 

X.UY14SIGNED = 1 or
X.UY15SIGNED = 1 or
X.U16SIGNED = 1 or
X.U17SIGNED = 1 or
X.U18SIGNED = 1 or
X.U19SIGNED = 1 or
X.U20SIGNED = 1 or

X.UY14ACTREF = 1 or
X.UY15ACTREF = 1 or
X.U16ACTREF = 1 or
X.U17ACTREF = 1 or
X.U18ACTREF = 1 or
X.U19ACTREF = 1 or
X.U20ACTREF = 1 or

X.UY14ACTFEE = 1 or
X.UY15ACTFEE = 1 or
X.U16ACTFEE = 1 or
X.U17ACTFEE = 1 or
X.U18ACTFEE = 1 or
X.U19ACTFEE = 1 or
X.U20ACTFEE = 1 or

X.USERDEF01 = 1 or
X.USERDEF02 = 1 or 
X.UNSOURCE = 1
)
and X.SYS_CHANGE_VERSION > @LastVersionNumber
) Y 
where Y.RECTYPE = 'BAU'






GO


