//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIFTGroup.GCTSC.Core.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using RIFTGroup.GCTSC.Core;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RiftEntities : DbContext
    {
        public RiftEntities()
            : base("name=RiftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SystemKey> SystemKeys { get; set; }
        public virtual DbSet<GCTSC_ExceptionLogging> GCTSC_ExceptionLogging { get; set; }
        public virtual DbSet<GCTSC_ChangeTracking> GCTSC_ChangeTracking { get; set; }
        public virtual DbSet<GCTSC_ChangeTracking_Requests> GCTSC_ChangeTracking_Requests { get; set; }
        public virtual DbSet<GCTSC_ChangeTracking_UpdateRequests> GCTSC_ChangeTracking_UpdateRequests { get; set; }
    
        public virtual int TESTs_ClearGCTSCChangeTrackingLogs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TESTs_ClearGCTSCChangeTrackingLogs");
        }
    
        public virtual int TESTs_ClearGCTSCExceptionTable()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TESTs_ClearGCTSCExceptionTable");
        }
    }
}
