//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIFTGroup.GCTSC.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT1
    {
        public string ACCOUNTNO { get; set; }
        public string COMPANY { get; set; }
        public string CONTACT { get; set; }
        public string LASTNAME { get; set; }
        public string DEPARTMENT { get; set; }
        public string TITLE { get; set; }
        public string SECR { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE2 { get; set; }
        public string PHONE3 { get; set; }
        public string FAX { get; set; }
        public string EXT1 { get; set; }
        public string EXT2 { get; set; }
        public string EXT3 { get; set; }
        public string EXT4 { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string COUNTRY { get; set; }
        public string DEAR { get; set; }
        public string SOURCE { get; set; }
        public string KEY1 { get; set; }
        public string KEY2 { get; set; }
        public string KEY3 { get; set; }
        public string KEY4 { get; set; }
        public string KEY5 { get; set; }
        public string STATUS { get; set; }
        public string NOTES { get; set; }
        public string MERGECODES { get; set; }
        public string CREATEBY { get; set; }
        public Nullable<System.DateTime> CREATEON { get; set; }
        public string CREATEAT { get; set; }
        public string OWNER { get; set; }
        public string LASTUSER { get; set; }
        public Nullable<System.DateTime> LASTDATE { get; set; }
        public string LASTTIME { get; set; }
        public string U_COMPANY { get; set; }
        public string U_CONTACT { get; set; }
        public string U_LASTNAME { get; set; }
        public string U_CITY { get; set; }
        public string U_STATE { get; set; }
        public string U_COUNTRY { get; set; }
        public string U_KEY1 { get; set; }
        public string U_KEY2 { get; set; }
        public string U_KEY3 { get; set; }
        public string U_KEY4 { get; set; }
        public string U_KEY5 { get; set; }
        public string recid { get; set; }
    }
}
