//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIFTGroup.GCTSC.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTSUPP
    {
        public string ACCOUNTNO { get; set; }
        public string RECTYPE { get; set; }
        public string CONTACT { get; set; }
        public string TITLE { get; set; }
        public string CONTSUPREF { get; set; }
        public string DEAR { get; set; }
        public string PHONE { get; set; }
        public string EXT { get; set; }
        public string FAX { get; set; }
        public string LINKACCT { get; set; }
        public string NOTES { get; set; }
        public string ADDRESS1 { get; set; }
        public string ADDRESS2 { get; set; }
        public string ADDRESS3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string COUNTRY { get; set; }
        public string MERGECODES { get; set; }
        public string STATUS { get; set; }
        public string LINKEDDOC { get; set; }
        public string LASTUSER { get; set; }
        public Nullable<System.DateTime> LASTDATE { get; set; }
        public string LASTTIME { get; set; }
        public string U_CONTACT { get; set; }
        public string U_CONTSUPREF { get; set; }
        public string U_ADDRESS1 { get; set; }
        public string recid { get; set; }
    }
}
