//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIFTGroup.GCTSC.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class GCTSC_ChangeTracking_Requests
    {
        public int Id { get; set; }
        public int ChangeTrackingId { get; set; }
        public string URL { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseContent { get; set; }
    
        public virtual GCTSC_ChangeTracking GCTSC_ChangeTracking { get; set; }
    }
}
