use GoldmineUAT

declare @synchronization_version nvarchar(max) = CHANGE_TRACKING_CURRENT_VERSION(); 

DECLARE @UEMAILADDR int = COLUMNPROPERTY(
   OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UEMAILADDR', 'ColumnId')

DECLARE @UCLIENTSTA int = COLUMNPROPERTY(
   OBJECT_ID('GoldmineUAT.dbo.CONTACT2'),'UCLIENTSTA', 'ColumnId')

SELECT  
    *, 
	[uemailaddrChanged] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UEMAILADDR, SYS_CHANGE_COLUMNS),	
	[uclientstaChanged] = 
	CHANGE_TRACKING_IS_COLUMN_IN_MASK(@UCLIENTSTA, SYS_CHANGE_COLUMNS)
FROM  
    CHANGETABLE(CHANGES GoldmineUAT.dbo.CONTACT2, 1) AS CT  